### PR TITLE
Fix the json.loads

### PR DESCRIPTION
**Pull request by rsbuilds**
Purpose: 

1. User should be able to json.loads the response for exception block. 
2. Changes in setup for quick deployment.

### CODE REVIEW

**Comment by Vinayakj009** [comment]
I have tested this pr and it works as expected.

**Comment by Vinayakj009** [comment]
I have tested this pr and it works as expected.

**Review by Vinayakj009 — APPROVED** [review]
I have tested this PR and it works as expected.

**Review by sashoeb94 — APPROVED** [review]
Works as expected. Loads into JSON as expected.

**Pull request merged**
